services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  flower:
    image: mher/flower:latest
    environment:
      FLOWER_PORT : 5555
      CELERY_BROKER_URL: "redis://redis:6379/0"
      FLOWER_BROKER_API: "redis://redis:6379/0"
    expose:
      - 5555
    ports:
      - '5555:5555'
    depends_on:
      - redis
  my-app:
    build: .
    image: my-app-image
    container_name: my-app-container2
    ports:
      - "5000:5000"
    depends_on:
      - flower
      - redis
  my-celery:
    image: my-app-image
    container_name: my-celery-container2
    command: celery -A app.xxx worker --loglevel=info
    depends_on:
      - flower
      - redis
      - my-app

volumes:
  cache:
    driver: local